# <Project>/configs/resnet_train.yaml
train_list: data/splits/exdark_train.txt

img_size: 640
batch_size: 10
epochs: 100
lr: 1.0e-4

pretrained: true
class_names_json: data/class_names.json
yolo_weights: yolov8n.pt
device: cuda

lambda_det: 1.0
lambda_identity: 0.05

out_dir: outputs/resnet_checkpoints
